### PR TITLE
Ported Cortex e2e modules, so we can reuse it smaller projects too.

### PR DESCRIPTION
**Pull request by bwplotka**
For awareness: @praccuci @pstibrany @kakkoyun porting our amazing integration suite to separate module. I cleaned this a little bit to make sure we import only minimum deps (see go.mod), otherwise it's drop-in.

Happy to give you write perms to this lib. We can move it totally different repo with proper release versioning etc, but this is not the problem I want to fix. Rather: large dep tree ( want to use e2e in many other smaller projects) 🤗 

PRs for Cortex and Thanos to propose using it (feel free to close those if we don't want this) to come.

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by kakkoyun** [comment]
Maybe we can create a `corthanos` organization for the shared dependencies?

**Comment by bwplotka** [comment]
Very fair point. We have already shared org. We could also put it in `prometheus-community` or something.

**Comment by bwplotka** [comment]
I think there is low motivation to spread the maintenance burden to separate repos as @praccuci mentioned. Some other option is to put this in Cortex in separate go.mod

**Comment by bwplotka** [comment]
Also looks like Thanos Team does not want rest of those tools (e.g testutil) to be depending on in Thanos, so I think I would just copy it here and syncing manually, we could the same with this framework

**Review by pracucci — APPROVED** [review]
Thanks @bwplotka for considering the e2e framework! I haven't deeply reviewed changes but I'm approving to mention I'm 💯  fine picking up the e2e framework we collaboratively worked on Cortex.

**Pull request merged**
